### ISSUE TITLE
All files

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.id-id#18]
All files in image folder are untranslated yet

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by olprod** [comment]
The locfile status shown InLocalization, waiting for checkedIn status. [ICMS QUERY](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=C%26E&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPlRydWU8L0lEPjxFTEM%2bRmFsc2U8L0VMQz48QU1QPkZhbHNlPC9BTVA%2bPFNPSFJJUj5GYWxzZTwvU09IUklSPjxTSFJQPkZhbHNlPC9TSFJQPjxTQVRPPkZhbHNlPC9TQVRPPjxTQUxPPlRydWU8L1NBTE8%2bPFFFPj4yPC9RRT48UVQ%2bPjxRUiBJZD0iMSIgQ1BJRD0iMCI%2bQ3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgU3RvcmU7RXF1YWw7TEFCX1BMLTMwMFQwMDwvUVI%2bPFFSIElkPSIyIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtMb2NGaWxlcztMYW5ndWFnZTtFcXVhbDtJbmRvbmVzaWFuIChJbmRvbmVzaWEpPC9RUj48UVIgSWQ9IjMiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgRmlsZSBSZWZlcmVuY2U7RXF1YWw7CWh0dHBzOi8vZ2l0aHViLmNvbS9NaWNyb3NvZnRMZWFybmluZy9QTC0zMDAtTWljcm9zb2Z0LVBvd2VyLUJJLURhdGEtQW5hbHlzdC9ibG9iL01haW4vSW5zdHJ1Y3Rpb25zLzAxLXByZXBhcmUtZGF0YS13aXRoLXBvd2VyLXF1ZXJ5LWluLXBvd2VyLWJpLWRlc2t0b3AubWQubWFuaWZlc3QueG1sPC9RUj48L1FUPjxSRz48R0M%2bTlVMTDwvR0M%2bPC9SRz48L1ZQUT4%3d)

**Comment by chriscarty00** [comment]
Not seeing the art loc in [Location ](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.id-id/tree/OLPRODLOC/Instructions/Linked_image_Files )

**Comment by chriscarty00** [comment]
Discusssed with PM - All images will not be localised going forward 
By design
